language: go
go:
  - "1.13.4"
services:
  - docker
sudo: false
notifications:
  email: false
os:
  - linux
before_install:
  - npm install -g codeclimate-test-reporter
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.22.2
install:
  - go mod tidy
jobs:
  include:
    - stage: lint
      script:
        - golangci-lint run
    - stage: test
      script:
        - cd cmd/volantmq
        - go build -v -gcflags "-N -l" .
        - cd ../..
        - ./go.test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - codeclimate-test-reporter < coverage.txt
    - stage: docker
      script:
        - ./dockerBuildLocal.sh
