[mqtt.tcp]
host="0.0.0.0"
port=1883
ssl_enable=true
ssl_cert_file="conf/cert.pem"
ssl_cert_key_file="conf/cert.key"


[[mqtt.auth.internal]]
user="testuser"
password="testpassword"

[[mqtt.auth.internal]]
user="testuser1"
password="testpassword1"

[log]
# options are: debug,info,warn,error,panic,fatal
level="debug"
# whether capture the trace info in error and above level logs.
enable_trace=true
